name: Kanar
description: "Run DangerJS to check if the PR is has a valid Jira ticket reference"

inputs:
  github_token:
    description: "Github authentification token"
    required: true
  jira_token:
    description: "Jira authentification token"
    required: true
  jira_token_user:
    description: "User email of Jira user the jira_token belongs to"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4.1.1
    - name: Install dependencies
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        NODE_PATH: ${{ github.action_path }}
      run: npm install
    - name: Run Danger
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        JIRA_TOKEN: ${{ inputs.jira_token }}
        JIRA_TOKEN_USER: ${{ inputs.jira_token_user }}
        NODE_PATH: ${{ github.action_path }}
      run: npx danger -i Kanarek --dangerfile ${{ github.action_path }}/dangerfile.js ci
