name: CliCop
description: "Run DangerJS to check if the PR is has a valid Clickup ticket reference"

inputs:
  github_token:
    description: "Github authentification token"
    required: true
  clickup_token:
    description: "Clickup authentification token"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4.1.1
    - name: Install dependencies
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        NODE_PATH: ${{ github.action_path }}
      run: npm install
    - name: Run Danger
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CLICKUP_TOKEN: ${{ inputs.clickup_token }}
        NODE_PATH: ${{ github.action_path }}
      run: npx danger -i CliCop --dangerfile ${{ github.action_path }}/dangerfile.js ci
